// I do not know how to do this
// https://m3.material.io/styles/color/roles
// https://m3.material.io/foundations/layout/understanding-layout/spacing
// https://material-foundation.github.io/material-theme-builder/

export const colors = {
    "description": "TYPE: CUSTOM\nMaterial Theme Builder export 2026-02-27 10:02:10",
    "seed": "#0592F7",
    "coreColors": {
        // "primary": "#0592F7",
        "primary": "#2989FF",
        "tertiary": "#2BA466"
    },
    "extendedColors": [],
    "schemes": {
        "light": {
            "primary": "#38608F",
            "surfaceTint": "#38608F",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#D2E4FF",
            "onPrimaryContainer": "#1C4975",
            "secondary": "#535F70",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#D7E3F8",
            "onSecondaryContainer": "#3C4858",
            "tertiary": "#2C6A46",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#B0F1C3",
            "onTertiaryContainer": "#0E5130",
            "error": "#BA1A1A",
            "onError": "#FFFFFF",
            "errorContainer": "#FFDAD6",
            "onErrorContainer": "#93000A",
            "background": "#F8F9FF",
            "onBackground": "#191C20",
            "surface": "#F8F9FF",
            "onSurface": "#191C20",
            "surfaceVariant": "#DFE2EB",
            "onSurfaceVariant": "#43474E",
            "outline": "#73777F",
            "outlineVariant": "#C3C6CF",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#2E3135",
            "inverseOnSurface": "#EFF0F7",
            "inversePrimary": "#A2C9FD",
            "primaryFixed": "#D2E4FF",
            "onPrimaryFixed": "#001C37",
            "primaryFixedDim": "#A2C9FD",
            "onPrimaryFixedVariant": "#1C4975",
            "secondaryFixed": "#D7E3F8",
            "onSecondaryFixed": "#101C2B",
            "secondaryFixedDim": "#BBC7DB",
            "onSecondaryFixedVariant": "#3C4858",
            "tertiaryFixed": "#B0F1C3",
            "onTertiaryFixed": "#00210F",
            "tertiaryFixedDim": "#94D5A8",
            "onTertiaryFixedVariant": "#0E5130",
            "surfaceDim": "#D8DAE0",
            "surfaceBright": "#F8F9FF",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#F2F3FA",
            "surfaceContainer": "#ECEEF4",
            "surfaceContainerHigh": "#E7E8EE",
            "surfaceContainerHighest": "#E1E2E8"
        },
        "light-medium-contrast": {
            "primary": "#003863",
            "surfaceTint": "#38608F",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#476F9E",
            "onPrimaryContainer": "#FFFFFF",
            "secondary": "#2B3747",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#626E7F",
            "onSecondaryContainer": "#FFFFFF",
            "tertiary": "#003F22",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#3B7953",
            "onTertiaryContainer": "#FFFFFF",
            "error": "#740006",
            "onError": "#FFFFFF",
            "errorContainer": "#CF2C27",
            "onErrorContainer": "#FFFFFF",
            "background": "#F8F9FF",
            "onBackground": "#191C20",
            "surface": "#F8F9FF",
            "onSurface": "#0E1116",
            "surfaceVariant": "#DFE2EB",
            "onSurfaceVariant": "#32363D",
            "outline": "#4E535A",
            "outlineVariant": "#696D75",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#2E3135",
            "inverseOnSurface": "#EFF0F7",
            "inversePrimary": "#A2C9FD",
            "primaryFixed": "#476F9E",
            "onPrimaryFixed": "#FFFFFF",
            "primaryFixedDim": "#2D5784",
            "onPrimaryFixedVariant": "#FFFFFF",
            "secondaryFixed": "#626E7F",
            "onSecondaryFixed": "#FFFFFF",
            "secondaryFixedDim": "#4A5666",
            "onSecondaryFixedVariant": "#FFFFFF",
            "tertiaryFixed": "#3B7953",
            "onTertiaryFixed": "#FFFFFF",
            "tertiaryFixedDim": "#21603D",
            "onTertiaryFixedVariant": "#FFFFFF",
            "surfaceDim": "#C5C6CC",
            "surfaceBright": "#F8F9FF",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#F2F3FA",
            "surfaceContainer": "#E7E8EE",
            "surfaceContainerHigh": "#DBDDE3",
            "surfaceContainerHighest": "#D0D1D7"
        },
        "light-high-contrast": {
            "primary": "#002D53",
            "surfaceTint": "#38608F",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#1F4B78",
            "onPrimaryContainer": "#FFFFFF",
            "secondary": "#212D3C",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#3E4A5A",
            "onSecondaryContainer": "#FFFFFF",
            "tertiary": "#00341B",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#115432",
            "onTertiaryContainer": "#FFFFFF",
            "error": "#600004",
            "onError": "#FFFFFF",
            "errorContainer": "#98000A",
            "onErrorContainer": "#FFFFFF",
            "background": "#F8F9FF",
            "onBackground": "#191C20",
            "surface": "#F8F9FF",
            "onSurface": "#000000",
            "surfaceVariant": "#DFE2EB",
            "onSurfaceVariant": "#000000",
            "outline": "#282C33",
            "outlineVariant": "#454951",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#2E3135",
            "inverseOnSurface": "#FFFFFF",
            "inversePrimary": "#A2C9FD",
            "primaryFixed": "#1F4B78",
            "onPrimaryFixed": "#FFFFFF",
            "primaryFixedDim": "#00345E",
            "onPrimaryFixedVariant": "#FFFFFF",
            "secondaryFixed": "#3E4A5A",
            "onSecondaryFixed": "#FFFFFF",
            "secondaryFixedDim": "#283343",
            "onSecondaryFixedVariant": "#FFFFFF",
            "tertiaryFixed": "#115432",
            "onTertiaryFixed": "#FFFFFF",
            "tertiaryFixedDim": "#003B20",
            "onTertiaryFixedVariant": "#FFFFFF",
            "surfaceDim": "#B7B9BF",
            "surfaceBright": "#F8F9FF",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#EFF0F7",
            "surfaceContainer": "#E1E2E8",
            "surfaceContainerHigh": "#D3D4DA",
            "surfaceContainerHighest": "#C5C6CC"
        },
        "dark": {
            "primary": "#A2C9FD",
            "surfaceTint": "#A2C9FD",
            "onPrimary": "#00325A",
            "primaryContainer": "#1C4975",
            "onPrimaryContainer": "#D2E4FF",
            "secondary": "#BBC7DB",
            "onSecondary": "#253141",
            "secondaryContainer": "#3C4858",
            "onSecondaryContainer": "#D7E3F8",
            "tertiary": "#94D5A8",
            "onTertiary": "#00391E",
            "tertiaryContainer": "#0E5130",
            "onTertiaryContainer": "#B0F1C3",
            "error": "#FFB4AB",
            "onError": "#690005",
            "errorContainer": "#93000A",
            "onErrorContainer": "#FFDAD6",
            "background": "#111418",
            "onBackground": "#E1E2E8",
            "surface": "#111418",
            "onSurface": "#E1E2E8",
            "surfaceVariant": "#43474E",
            "onSurfaceVariant": "#C3C6CF",
            "outline": "#8D9199",
            "outlineVariant": "#43474E",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#E1E2E8",
            "inverseOnSurface": "#2E3135",
            "inversePrimary": "#38608F",
            "primaryFixed": "#D2E4FF",
            "onPrimaryFixed": "#001C37",
            "primaryFixedDim": "#A2C9FD",
            "onPrimaryFixedVariant": "#1C4975",
            "secondaryFixed": "#D7E3F8",
            "onSecondaryFixed": "#101C2B",
            "secondaryFixedDim": "#BBC7DB",
            "onSecondaryFixedVariant": "#3C4858",
            "tertiaryFixed": "#B0F1C3",
            "onTertiaryFixed": "#00210F",
            "tertiaryFixedDim": "#94D5A8",
            "onTertiaryFixedVariant": "#0E5130",
            "surfaceDim": "#111418",
            "surfaceBright": "#37393E",
            "surfaceContainerLowest": "#0B0E13",
            "surfaceContainerLow": "#191C20",
            "surfaceContainer": "#1D2024",
            "surfaceContainerHigh": "#272A2F",
            "surfaceContainerHighest": "#32353A"
        },
        "dark-medium-contrast": {
            "primary": "#C8DEFF",
            "surfaceTint": "#A2C9FD",
            "onPrimary": "#002748",
            "primaryContainer": "#6C93C4",
            "onPrimaryContainer": "#000000",
            "secondary": "#D1DDF1",
            "onSecondary": "#1B2635",
            "secondaryContainer": "#8592A4",
            "onSecondaryContainer": "#000000",
            "tertiary": "#AAEBBD",
            "onTertiary": "#002C16",
            "tertiaryContainer": "#5F9E75",
            "onTertiaryContainer": "#000000",
            "error": "#FFD2CC",
            "onError": "#540003",
            "errorContainer": "#FF5449",
            "onErrorContainer": "#000000",
            "background": "#111418",
            "onBackground": "#E1E2E8",
            "surface": "#111418",
            "onSurface": "#FFFFFF",
            "surfaceVariant": "#43474E",
            "onSurfaceVariant": "#D9DCE5",
            "outline": "#AEB2BA",
            "outlineVariant": "#8C9099",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#E1E2E8",
            "inverseOnSurface": "#272A2F",
            "inversePrimary": "#1D4A76",
            "primaryFixed": "#D2E4FF",
            "onPrimaryFixed": "#001226",
            "primaryFixedDim": "#A2C9FD",
            "onPrimaryFixedVariant": "#003863",
            "secondaryFixed": "#D7E3F8",
            "onSecondaryFixed": "#061220",
            "secondaryFixedDim": "#BBC7DB",
            "onSecondaryFixedVariant": "#2B3747",
            "tertiaryFixed": "#B0F1C3",
            "onTertiaryFixed": "#001508",
            "tertiaryFixedDim": "#94D5A8",
            "onTertiaryFixedVariant": "#003F22",
            "surfaceDim": "#111418",
            "surfaceBright": "#42454A",
            "surfaceContainerLowest": "#05080B",
            "surfaceContainerLow": "#1B1E22",
            "surfaceContainer": "#25282D",
            "surfaceContainerHigh": "#303338",
            "surfaceContainerHighest": "#3B3E43"
        },
        "dark-high-contrast": {
            "primary": "#E9F0FF",
            "surfaceTint": "#A2C9FD",
            "onPrimary": "#000000",
            "primaryContainer": "#9EC5F9",
            "onPrimaryContainer": "#000C1C",
            "secondary": "#E9F0FF",
            "onSecondary": "#000000",
            "secondaryContainer": "#B7C3D7",
            "onSecondaryContainer": "#020C1A",
            "tertiary": "#BEFFD1",
            "onTertiary": "#000000",
            "tertiaryContainer": "#90D1A5",
            "onTertiaryContainer": "#000F05",
            "error": "#FFECE9",
            "onError": "#000000",
            "errorContainer": "#FFAEA4",
            "onErrorContainer": "#220001",
            "background": "#111418",
            "onBackground": "#E1E2E8",
            "surface": "#111418",
            "onSurface": "#FFFFFF",
            "surfaceVariant": "#43474E",
            "onSurfaceVariant": "#FFFFFF",
            "outline": "#EDF0F9",
            "outlineVariant": "#BFC3CB",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#E1E2E8",
            "inverseOnSurface": "#000000",
            "inversePrimary": "#1D4A76",
            "primaryFixed": "#D2E4FF",
            "onPrimaryFixed": "#000000",
            "primaryFixedDim": "#A2C9FD",
            "onPrimaryFixedVariant": "#001226",
            "secondaryFixed": "#D7E3F8",
            "onSecondaryFixed": "#000000",
            "secondaryFixedDim": "#BBC7DB",
            "onSecondaryFixedVariant": "#061220",
            "tertiaryFixed": "#B0F1C3",
            "onTertiaryFixed": "#000000",
            "tertiaryFixedDim": "#94D5A8",
            "onTertiaryFixedVariant": "#001508",
            "surfaceDim": "#111418",
            "surfaceBright": "#4D5055",
            "surfaceContainerLowest": "#000000",
            "surfaceContainerLow": "#1D2024",
            "surfaceContainer": "#2E3135",
            "surfaceContainerHigh": "#393B40",
            "surfaceContainerHighest": "#44474C"
        }
    },
    "palettes": {
        "primary": {
            "0": "#000000",
            "5": "#001225",
            "10": "#001C37",
            "15": "#002748",
            "20": "#00325A",
            "25": "#003D6C",
            "30": "#00497F",
            "35": "#005493",
            "40": "#0061A7",
            "50": "#007AD0",
            "60": "#0F94F9",
            "70": "#68AFFF",
            "80": "#A0C9FF",
            "90": "#D2E4FF",
            "95": "#EAF1FF",
            "98": "#F8F9FF",
            "99": "#FDFCFF",
            "100": "#FFFFFF"
        },
        "secondary": {
            "0": "#000000",
            "5": "#001225",
            "10": "#091C31",
            "15": "#15273C",
            "20": "#203147",
            "25": "#2B3D52",
            "30": "#37485E",
            "35": "#42546B",
            "40": "#4E6077",
            "50": "#677891",
            "60": "#8092AB",
            "70": "#9BADC7",
            "80": "#B6C8E3",
            "90": "#D2E4FF",
            "95": "#EAF1FF",
            "98": "#F8F9FF",
            "99": "#FDFCFF",
            "100": "#FFFFFF"
        },
        "tertiary": {
            "0": "#000000",
            "5": "#001508",
            "10": "#00210F",
            "15": "#002D16",
            "20": "#00391E",
            "25": "#004526",
            "30": "#00522E",
            "35": "#005F36",
            "40": "#006D3E",
            "50": "#008950",
            "60": "#2BA466",
            "70": "#4DC07F",
            "80": "#6ADC98",
            "90": "#87F9B3",
            "95": "#C2FFD3",
            "98": "#E9FFEC",
            "99": "#F5FFF4",
            "100": "#FFFFFF"
        },
        "neutral": {
            "0": "#000000",
            "5": "#0F1114",
            "10": "#1A1C1E",
            "15": "#242629",
            "20": "#2F3033",
            "25": "#3A3B3E",
            "30": "#45474A",
            "35": "#515255",
            "40": "#5D5E61",
            "50": "#76777A",
            "60": "#909094",
            "70": "#ABABAE",
            "80": "#C6C6CA",
            "90": "#E3E2E6",
            "95": "#F1F0F4",
            "98": "#FAF9FD",
            "99": "#FDFCFF",
            "100": "#FFFFFF"
        },
        "neutral-variant": {
            "0": "#000000",
            "5": "#0D1117",
            "10": "#171C22",
            "15": "#22262D",
            "20": "#2C3137",
            "25": "#373C43",
            "30": "#43474E",
            "35": "#4E535A",
            "40": "#5A5F66",
            "50": "#73777F",
            "60": "#8D9199",
            "70": "#A7ABB4",
            "80": "#C3C6CF",
            "90": "#DFE2EB",
            "95": "#EDF1FA",
            "98": "#F8F9FF",
            "99": "#FDFCFF",
            "100": "#FFFFFF"
        }
    }
};

interface Sizing {
    "4xs": number;
    "3xs": number;
    "2xs": number;
    xs: number;
    sm: number;
    md: number;
    base: number;
    lg: number;
    xl: number;
    "2xl": number;
    "3xl": number;
    "4xl": number;
};

export const ZERO_SIZING: Sizing = {
    "4xs": 0,
    "3xs": 0,
    "2xs": 0,
    xs: 0,
    sm: 0,
    md: 0,
    base: 0,
    lg: 0,
    xl: 0,
    "2xl":0,
    "3xl":0,
    "4xl":0
};

export const margin: Sizing = Object.assign({}, ZERO_SIZING, {
    "3xs": 8,
    "2xs": 12,
    xs: 20,
    sm: 24,
    md: 28,
    lg: 36,
    xl: 48
});

export const spacing: Sizing = Object.assign({}, ZERO_SIZING, {
    xs: 16,
    sm: 20,
    md: 24,
    lg: 28,
    xl: 32
});

export const padding: Sizing = Object.assign({}, ZERO_SIZING, {
    xs: 2,
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    "2xl": 24,
    "4xl": 32
});

export const shadow = {
    sm: {
        shadowColor: colors.schemes.light.shadow,
        shadowOpacity: 0.05,
        shadowRadius: 1,
        shadowOffset: {
            width: 0,
            height: 1
        }
    },
    md: {
        shadowColor: colors.schemes.light.shadow,
        shadowOpacity: 0.075,
        shadowRadius: 2,
        shadowOffset: {
            width: 0,
            height: 2
        }
    },
    lg: {
        shadowColor: colors.schemes.light.shadow,
        shadowOpacity: 0.075,
        shadowRadius: 3,
        shadowOffset: {
            width: 0,
            height: 4
        }
    }
}

export const borderRadius: Sizing = Object.assign({}, ZERO_SIZING, {
    sm: 6,
    md: 8,
    base: 10,
    lg: 12,
    xl: 20
});

export const fontSize: Sizing = Object.assign({}, ZERO_SIZING, {
    xs: 10,
    sm: 12,
    md: 14,
    base: 16,
    lg: 18,
    xl: 24,
    "2xl": 32,
    "3xl": 40,
    "4xl": 60
});

export const letterSpacing: Sizing = Object.assign({}, ZERO_SIZING, {
    "2xs": -0.5,
    xs: -0.25,
    sm: -0.1,
    base: 0,
    lg: 0.1,
    xl: 0.25,
    "2xl": 0.5
});

export const theme = {
    fontSize,
    letterSpacing,
    borderRadius,
    shadow,
    padding,
    spacing,
    margin,
    colors
}