# Generated by Django 6.0.2 on 2026-04-10 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mode', models.CharField(max_length=255)),
                ('notificationType', models.CharField(default='NONE', max_length=255)),
                ('profilePicture', models.CharField(blank=True, max_length=255, null=True)),
                ('profileBackgroundColor', models.CharField(default='#FFFFFF', max_length=255)),
                ('isDarkMode', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward'), ('CO', 'Coach'), ('US', 'Unselected')], default='US', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drillName', models.CharField(max_length=255)),
                ('drillType', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('difficultyLevel', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
                ('publicDrill', models.BooleanField(default=False)),
                ('coachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrillBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.drill')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.CharField(max_length=50)),
                ('iconBackground', models.CharField(default='#FFFFFF', max_length=7)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=255)),
                ('classCode', models.CharField(blank=True, max_length=5)),
                ('imageText', models.CharField(blank=True, max_length=5)),
                ('imageTextColor', models.CharField(blank=True, max_length=50)),
                ('imageBackgroundColor', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True)),
                ('assignments', models.ManyToManyField(blank=True, related_name='soccer_classes', to='futbolfrenzy.assignment')),
                ('coachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='futbolfrenzy.soccerclass')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('dateGraded', models.DateTimeField(blank=True, null=True)),
                ('dateSubmitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
                ('assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.assignment')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoURL', models.URLField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('touchCount', models.IntegerField(blank=True, null=True)),
                ('drillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.drill')),
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutName', models.CharField(max_length=255)),
                ('workoutType', models.CharField(max_length=255)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
                ('publicWorkout', models.BooleanField(default=False)),
                ('coachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='workoutID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.workout'),
        ),
        migrations.CreateModel(
            name='WorkoutBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workoutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('drillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.drill')),
                ('workoutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='drills',
            field=models.ManyToManyField(related_name='workouts', through='futbolfrenzy.WorkoutDrill', to='futbolfrenzy.drill'),
        ),
    ]
