# Generated by Django 6.0.2 on 2026-03-03 00:55

import django.db.models.deletion
# Generated by Django 6.0.2 on 2026-03-01 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drillName', models.CharField(max_length=255)),
                ('coachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('dueDate', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('coachID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_drills', to=settings.AUTH_USER_MODEL)),
                ('drillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.drill')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_drills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
