# Generated by Django 6.0.2 on 2026-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccerclass',
            name='classCode',
            field=models.CharField(max_length=5, blank=True),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='imageText',
            field=models.CharField(max_length=5, blank=True),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='imageTextColor',
            field=models.CharField(max_length=50, blank=True),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='imageBackgroundColor',
            field=models.CharField(max_length=50, blank=True),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
