# Generated by Django 6.0.2 on 2026-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='coachID',
            field=models.CharField(max_length=255),
        ),
    ]
