# Generated by Django 6.0.2 on 2026-03-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='difficultyLevel',
            field=models.CharField(default='Beginner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='drillType',
            field=models.CharField(default='DrillType', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='imageBackgroundColor',
            field=models.CharField(default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='imageText',
            field=models.CharField(default='ImageText', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='imageTextColor',
            field=models.CharField(default='#000000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='instructions',
            field=models.TextField(default='Instructions Here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='publicDrill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drill',
            name='time',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drill',
            name='url',
            field=models.URLField(default='www.thisisaURL.com'),
            preserve_default=False,
        ),
    ]
