# Generated by Django 6.0.2 on 2026-03-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0002_drill_difficultylevel_drill_drilltype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutName', models.CharField(max_length=255)),
                ('workoutType', models.CharField(max_length=255)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
                ('publicWorkout', models.BooleanField(default=False)),
                ('drills', models.ManyToManyField(related_name='drills', to='futbolfrenzy.drill')),
            ],
        ),
    ]
