# Generated by Django 6.0.2 on 2026-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0002_add_missing_soccerclass_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteddrill',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
