# Generated by Django 6.0.2 on 2026-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0003_submitteddrill_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteddrill',
            name='suggestedGrade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
