# Generated by Django 6.0.2 on 2026-03-03 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0004_workout_coachid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
                ('workoutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
