# Generated by Django 6.0.2 on 2026-03-03 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0006_soccerclass_classmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('dateGraded', models.DateTimeField(blank=True, null=True)),
                ('dateSubmitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageBackgroundColor', models.CharField(max_length=7)),
                ('imageText', models.CharField(max_length=255)),
                ('imageTextColor', models.CharField(max_length=255)),
                ('assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.assignment')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoURL', models.URLField()),
                ('grade', models.IntegerField()),
                ('touchCount', models.IntegerField()),
                ('drillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.drill')),
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.submission')),
            ],
        ),
    ]
