# Generated by Django 6.0.2 on 2026-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0007_submission_submitteddrill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitteddrill',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
