# Generated by Django 6.0.2 on 2026-03-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0008_alter_submission_grade_alter_submitteddrill_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteddrill',
            name='touchCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
