# Generated by Django 6.0.2 on 2026-03-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0010_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='profileBackgroundColor',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
    ]
