# Generated by Django 6.0.2 on 2026-03-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0011_alter_settings_profilebackgroundcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='videoDrill',
            field=models.FileField(default='tempvid/example.gif', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='submitteddrill',
            name='videoSubmission',
            field=models.FileField(default='tempvid/example.gif', upload_to='uploads/'),
        ),
    ]
