# Generated by Django 6.0.2 on 2026-03-07 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0011_alter_settings_profilebackgroundcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='workoutID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.workout'),
        ),
    ]
