# Generated by Django 6.0.2 on 2026-03-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0012_alter_assignment_workoutid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerclass',
            name='assignments',
            field=models.ManyToManyField(related_name='assignments', to='futbolfrenzy.assignment'),
        ),
    ]
