# Generated by Django 6.0.2 on 2026-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0013_alter_soccerclass_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerclass',
            name='assignments',
            field=models.ManyToManyField(related_name='soccer_classes', to='futbolfrenzy.assignment'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='drills',
            field=models.ManyToManyField(related_name='workouts', to='futbolfrenzy.drill'),
        ),
    ]
