# Generated by Django 6.0.2 on 2026-03-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0014_alter_soccerclass_assignments_alter_workout_drills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='classID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='futbolfrenzy.soccerclass'),
        ),
    ]
