# Generated by Django 6.0.2 on 2026-03-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0015_alter_classmember_classid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
