# Generated by Django 6.0.2 on 2026-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0015_alter_classmember_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='isDarkMode',
            field=models.BooleanField(default=False),
        ),
    ]
