# Generated by Django 6.0.2 on 2026-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0016_notification_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='read',
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='graded', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='iconBackground',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
