# Generated by Django 6.0.2 on 2026-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0017_rename_body_notification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccerclass',
            name='classCode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='soccerclass',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='soccer_classes', to='futbolfrenzy.assignment'),
        ),
    ]
