# Generated by Django 6.0.2 on 2026-03-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0018_drillbookmark_workoutbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='time',
        ),
    ]
