# Generated by Django 6.0.2 on 2026-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0018_soccerclass_classcode_alter_soccerclass_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccerclass',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='imageBackgroundColor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='imageText',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='soccerclass',
            name='imageTextColor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
