# Generated by Django 6.0.2 on 2026-03-31 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0019_remove_drill_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('drillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.drill')),
                ('workoutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolfrenzy.workout')),
            ],
        ),
    ]
