# Generated by Django 6.0.2 on 2026-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0019_soccerclass_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
