# Generated by Django 6.0.2 on 2026-03-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0020_workoutdrill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='drills',
        ),
    ]
