# Generated by Django 6.0.2 on 2026-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0021_remove_workout_drills'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='drills',
            field=models.ManyToManyField(related_name='workouts', through='futbolfrenzy.WorkoutDrill', to='futbolfrenzy.drill'),
        ),
    ]
