# Generated by Django 6.0.2 on 2026-04-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0016_delete_enrollment'),
        ('futbolfrenzy', '0022_workout_drills'),
    ]

    operations = [
    ]
