# Generated by Django 6.0.2 on 2026-03-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0017_remove_settings_id_alter_settings_userid'),
        ('futbolfrenzy', '0022_workout_drills'),
    ]

    operations = [
    ]
