# Generated by Django 6.0.2 on 2026-04-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0019_soccerclass_description_and_more'),
        ('futbolfrenzy', '0023_merge_20260331_2204'),
    ]

    operations = [
    ]
