# Generated by Django 6.0.2 on 2026-04-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolfrenzy', '0023_merge_0016_delete_enrollment_0022_workout_drills'),
        ('futbolfrenzy', '0024_merge_20260401_0322'),
    ]

    operations = [
    ]
